[package]
name = "podman-compose-mgr"
version = "0.1.1"
edition = "2021"

[dependencies]
walkdir = "2"
regex = "1"
clap = { version = "4", features = ["derive"] }
#term_size = "0"
chrono = "0"
serde_yaml = "0"
dockerfile-parser = "0"
reqwest = { version = "0", features = ["json", "blocking"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
md-5 = "0"
tokio = { version = "1", features = ["full"] }
azure_identity = "0.21"
azure_security_keyvault = "0"
time = "0"
hostname = "0"
terminal_size = "0"

[dev-dependencies]
tempfile = "3"  # Use the latest version
mockall = "0.12.1"
